version: '3.8'

networks:
  workchat:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: EmailDomainsDb, PersonalDataDb, EmployeesDb
    ports:
      - "5432:5432"
    networks:
      - workchat
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: on-failure

  wc-service-emaildomains:
    image: saintefim/wc-service-emaildomains:latest
    container_name: wc.service.emaildomains.api
    ports:
      - "1002:1002"
      - "2002:2002"
    depends_on:
      postgres:
        condition: service_healthy  # Ждём готовности БД
    networks:
      - workchat
    restart: on-failure

  wc-service-registration:
    image: saintefim/wc-service-registration:latest
    container_name: wc.service.registration.api
    ports:
      - "1001:1001"
    depends_on:
      wc-service-emaildomains:
        condition: service_started
    networks:
      - workchat
    restart: on-failure

  wc-service-employees:
    image: saintefim/wc-service-employees:latest
    container_name: wc.service.employees.api
    ports:
      - "1003:1003"
      - "2003:2003"
    depends_on:
      wc-service-emaildomains:
        condition: service_started
    networks:
      - workchat
    restart: on-failure

  wc-service-personaldata:
    image: saintefim/wc-service-personaldata:latest
    container_name: wc.service.personaldata
    ports:
      - "1004:1004"
      - "2004:2004"
    depends_on:
      wc-service-employees:
        condition: service_started
    networks:
      - workchat
    restart: on-failure

  wc-service-authentication:
    image: saintefim/wc-service-authentication:latest
    container_name: wc.service.authentication.api
    ports:
      - "1005:1005"
      - "2005:2005"
    depends_on:
      wc-service-personaldata:
        condition: service_started
    networks:
      - workchat
    restart: on-failure

  # --- ОТДЕЛЬНЫЙ БЛОК ДЛЯ ПОСЛЕДОВАТЕЛЬНОГО ЗАПУСКА 4 КОНТЕЙНЕРОВ ---
  
  wc-service-emaildomains-createdomain:
    image: saintefim/wc-service-emaildomains-createdomain:latest
    container_name: wc.service.emaildomains.createdomain
    depends_on:
      wc-service-authentication:
        condition: service_started  # Ждём, пока ВСЕ основные сервисы запустятся
    networks:
      - workchat

  wc-service-employees-createposition:
    image: saintefim/wc-service-employees-createposition:latest
    container_name: wc.service.employees.createposition
    depends_on:
      wc-service-emaildomains-createdomain:
        condition: service_started
    networks:
      - workchat

  wc-service-registration-createadmin:
    image: saintefim/wc-service-registration-createadmin:latest
    container_name: wc.service.registration.createadmin
    depends_on:
      wc-service-employees-createposition:
        condition: service_started
    networks:
      - workchat

  wc-service-authentication-authorizationadmin:
    image: saintefim/wc-service-authentication-authorizationadmin:latest
    container_name: wc.service.authentication.authorizationadmin
    depends_on:
      wc-service-registration-createadmin:
        condition: service_started
    networks:
      - workchat
    restart: on-failure
