version: '3.8'

networks:
  workchat:
    driver: bridge

x-environment:
  # Общие настройки для всех сервисов
  common-env: &common-env
    ASPNETCORE_ENVIRONMENT: Development

  # Настройки для админских сервисов
  common-admin-env: &common-admin-env
    AdminSettings__AdminEmailLocalPart: "admin"
    AdminSettings__AdminEmailDomain: "admin.com"
    AdminSettings__AdminRegistrationPassword: "Admin@12345678"
    AdminSettings__AdminPositionId: "00000000-0000-0000-0000-000000000001"
    AdminSettings__AdminRegistrationName: "Админ"
    AdminSettings__AdminRegistrationSurname: "Админ"
    AdminSettings__AdminRegistrationPatronymic: "Админович"

  # Настройки для доменных сервисов (например, email домены)
  common-domain-env: &common-domain-env
    AdminSettings__EmailDomains__0: "admin.com"
    AdminSettings__EmailDomains__1: "example.com"
    AdminSettings__EmailDomains__2: "mydomain.com"

  # Настройки для позиций (используются для создания позиций пользователей)
  common-position-env: &common-position-env
    AdminSettings__PositionNames__0: "Администратор"
    AdminSettings__PositionNames__1: "Пользователь"
    AdminSettings__PositionNames__2: "Менеджер"
    AdminSettings__AdminPositionId: "00000000-0000-0000-0000-000000000001"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ChatsDb
    ports:
      - "5432:5432"
    networks:
      - workchat
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: on-failure

  wc-service-registration:
    image: saintefim/wc-service-registration:latest
    container_name: wc.service.registration.api
    ports:
      - "1001:1001"
    depends_on:
      - postgres
    environment:
      <<: *common-env
      Services__employees: http://wc-service-employees:2003
      Services__authentication: http://wc-service-authentication:2005
    networks:
      - workchat
    restart: on-failure

  wc-service-emaildomains:
    image: saintefim/wc-service-emaildomains:latest
    container_name: wc.service.emaildomains.api
    ports:
      - "1002:1002"
      - "2002:2002"
    depends_on:
      - wc-service-registration
    environment:
      <<: *common-env
      Services_personal-data: http://wc-service-personaldata:2004
      ConnectionStrings__ServiceDB: Host=postgres;Database=EmailDomainsDb;Username=postgres;Password=1234
    networks:
      - workchat
    restart: on-failure

  wc-service-employees:
    image: saintefim/wc-service-employees:latest
    container_name: wc.service.employees.api
    ports:
      - "1003:1003"
      - "2003:2003"
    depends_on:
      - wc-service-emaildomains
    environment:
      <<: *common-env
      Services_personal-data: http://wc-service-personaldata:2004
      ConnectionStrings__ServiceDB: "Host=postgres;Database=EmployeesDb;Username=postgres;Password=1234"
    networks:
      - workchat
    restart: on-failure

  wc-service-personaldata:
    image: saintefim/wc-service-personaldata:latest
    container_name: wc.service.personaldata
    ports:
      - "1004:1004"
      - "2004:2004"
    depends_on:
      - wc-service-employees
    environment:
      <<: *common-env
      ConnectionStrings__ServiceDB: "Host=postgres;Database=PersonalDataDb;Username=postgres;Password=1234"
      Services__email-domains: http://wc-service-emaildomains:2002
    networks:
      - workchat
    restart: on-failure

  wc-service-authentication:
    image: saintefim/wc-service-authentication:latest
    container_name: wc.service.authentication.api
    ports:
      - "1005:1005"
      - "2005:2005"
    depends_on:
      - wc-service-personaldata
    environment:
      <<: *common-env
      Services_personal-data: http://wc-service-personaldata:2004
    networks:
      - workchat
    restart: on-failure

  chats-service:
    image: saintefim/chats-service:latest
    container_name: chats-service
    ports:
      - "1006:1006"
      - "2006:2006"
    depends_on:
      - postgres
    volumes:
      - ./configs/chats/config.yaml:/app/config/config.yaml:ro
    networks:
      - workchat
    restart: on-failure

  messages-service:
    image: saintefim/messages-service:latest
    container_name: messages-service
    ports:
      - "1007:1007"
      - "2007:2007"
    depends_on:
      - chats-service
    volumes:
      - ./configs/messages/config.yaml:/app/config/config.yaml:ro
    networks:
      - workchat
    restart: on-failure

  wc-service-emaildomains-createdomain:
    image: saintefim/wc-service-emaildomains-createdomain:latest
    container_name: wc.service.emaildomains.createdomain
    depends_on:
      - chats-service
    environment:
      <<: [ *common-domain-env, *common-env ]
    networks:
      - workchat

  wc-service-employees-createposition:
    image: saintefim/wc-service-employees-createposition:latest
    container_name: wc.service.employees.createposition
    depends_on:
      - wc-service-emaildomains-createdomain
    environment:
      <<: [ *common-admin-env, *common-position-env, *common-env ]
      Services_personal-data: http://wc-service-personaldata:2004
    networks:
      - workchat

  wc-service-registration-createadmin:
    image: saintefim/wc-service-registration-createadmin:latest
    container_name: wc.service.registration.createadmin
    depends_on:
      - wc-service-employees-createposition
    environment:
      <<: [ *common-admin-env, *common-env ]
      Services__employees: http://wc-service-employees:2003
      Services__authentication: http://wc-service-authentication:2005
    networks:
      - workchat

  wc-service-authentication-authorizationadmin:
    image: saintefim/wc-service-authentication-authorizationadmin:latest
    container_name: wc.service.authentication.authorizationadmin
    depends_on:
      - wc-service-registration-createadmin
    environment:
      <<: [ *common-admin-env, *common-env ]
      Services_personal-data: http://wc-service-personaldata:2004
    networks:
      - workchat
    restart: on-failure
