networks:
  workchat:
    driver: bridge

services:
  workchat-client:
    image: merk9ayt/workchat:latest
    container_name: workchat-client
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    networks:
      - workchat
    restart: on-failure