HTTPServer:
  Addr: "0.0.0.0"
  Port: "1006"
  Timeout: 5
EnvironmentVariables:
  Environment: "development"
DataBase:
  ConnectionString: "postgres://postgres:1234@localhost/ChatsDb?sslmode=disable"
  ConnectionPostgres: "postgres://postgres:1234@localhost:5432/postgres?sslmode=disable"
  Name: "ChatsDb"
GRPCClient:
  Services:
    employees: "0.0.0.0:2003"
GRPCServer:
  Type: "tcp"
  Addr: ":2006"
Logs:
  Path: ""
  Level: info
  MaxAge: 1
  MaxBackups: 4
Cors:
  "AllowedOrigins": [
    "http://localhost:4200"
  ]
AuthenticationConfiguration:
  AccessSecretKey: "tM+Lm9iti8KzwHNeHXVzQrIcMm8GNIFjf73UiZpKnP4="
