EnvironmentVariables:
  Environment: "development"
Server:
  Addr: "0.0.0.0"
  Port: "1007"
  Timeout: 5
Logs:
  Path: ""
  Level: info
  MaxAge: 1
  MaxBackups: 4
GRPCClient:
  Services:
      chats: "chats-service:2006"
Cors:
  AllowedOrigins: ["http://192.168.31.48:4200", "http://localhost:4200"]
AuthenticationConfiguration:
  AccessSecretKey: "tM+Lm9iti8KzwHNeHXVzQrIcMm8GNIFjf73UiZpKnP4="



